#!/usr/bin/env bash
# display numbers from 1 to 20 while inserting text between numbers
i=1
while [ $i -le 20 ]
do
	echo "$i"
	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck form Italy"
			;;
	esac
	i=$((i+1))
done	
