#!/usr/bin/env bash
# Check if the file 'school' exists
if [[ -e school ]]; then 
    if [[ -f school ]]; then
        echo "school is a regular file"
    fi
    if [[ ! -s school ]]; then
        echo "school file is empty"
    else
        echo "school file is not empty"
    fi
    
    echo "school file exists"

else
    echo "school file does not exist"
fi
