#!/usr/bin/env bash
# has done everything
echo $$ > /var/run/myscript.pid

# Function to handle SIGTERM and SIGQUIT
trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit' SIGTERM SIGQUIT

# Function to handle SIGINT (Ctrl+C)
trap 'echo "Y U no love me?!"' SIGINT

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
